name: Build and Create Release (main)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/_build.yml
        
  deploy:
    name: Deploy Pre-Release NuGet Packages to Repository Packages
    needs: build
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true      
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache
         
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Push Pre-Release Package to GitHub Packages
        if: (format('{0}', env.PACKAGE_KEY) != '')
        shell: pwsh
        run: dotnet nuget push *.nupkg --api-key ${{ env.PACKAGE_KEY }} --source "https://nuget.pkg.github.com/robgray/index.json" --skip-duplicate
        working-directory: ./NuGet Packages/
        env:
          PACKAGE_KEY: ${{ secrets.PACKAGE_UPLOAD }}

      - name: Delete Old Packages
        uses: smartsquaregmbh/delete-old-packages@v0.8.0
        with:
          user: robgray
          type: nuget
          keep: 5
          dry-run: true
          names: |
            Ragware.QnapPhotoApi